### PR TITLE
Feat/eugene/postcard bindgen

### PR DESCRIPTION
**Pull request by 0xterminator**
[Link to related issue(s) here, if any]

[Short description of the changes.]

## Checklist
- [ ] Breaking changes are clearly marked as such in the PR description and changelog
- [ ] New behavior is reflected in tests
- [ ] If performance characteristic of an instruction change, update gas costs as well or make a follow-up PR for that
- [ ] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [ ] I have reviewed the code myself
- [ ] I have created follow-up issues caused by this PR and linked them here

### After merging, notify other teams

[Add or remove entries as needed]

- [ ] [Rust SDK](https://github.com/FuelLabs/fuels-rs/)
- [ ] [Sway compiler](https://github.com/FuelLabs/sway/)
- [ ] [Platform documentation](https://github.com/FuelLabs/devrel-requests/issues/new?assignees=&labels=new+request&projects=&template=NEW-REQUEST.yml&title=%5BRequest%5D%3A+) (for out-of-organization contributors, the person merging the PR will do this)
- [ ] Someone else?

### CODE REVIEW

**Comment by xgreenx** [comment]
What is the purpose of this PR?=)

**Comment by 0xterminator** [comment]
> What is the purpose of this PR?=)

It is just a draft, I am experimenting with adding postcard to js bindings.

**Comment by xgreenx** [comment]
Why do you need it?=) You can use `from_json` and `to_json` function in WASM, if you want to

**Comment by 0xterminator** [comment]
> Why do you need it?=) You can use `from_json` and `to_json` function in WASM, if you want to

I know, but what we want to see is whether we can attach this crate https://github.com/teamplayer3/postcard-bindgen so we generate for all structures that we want to stream over nats ser/deser functionalities using postcard and also have an auto-generated npm package for our ts-sdk (fuel-systems_) in order to have 1:1 serialization/deserialization of the same structures.

**Comment by 0xterminator** [comment]
Closing as this research did not lead to the desired effect @pedronauck

**Pull request closed without merging**
