### PR TITLE
Allow backwards jumps in the predicates

### PR DESCRIPTION
**Pull request by Voxelot**
Before release [v0.26.1](https://github.com/FuelLabs/fuel-vm/releases/tag/v0.26.1):

*do not merge*

Master branch now contains breaking changes we don't want to include into fuel-core 0.17.x. This branch is a hotfix patch release that is fixing the behavior of predicates to allow backwards jumps. This PR is just serving as a means of recording this change and to verify CI passes.

After release we create a release [v0.26.1](https://github.com/FuelLabs/fuel-vm/releases/tag/v0.26.1) based on this branch:

Now we can and need to merge it into the master because the release `0.26.1` contains this change.

### CODE REVIEW

**Comment by xgreenx** [comment]
I think we still want to merge it into the master to have it for future releases=)

**Review by xgreenx — APPROVED** [review]
@Voxelot should merge it, if he agrees =)

**Comment by Voxelot** [comment]
We shouldn't merge this, as the change has already been done in other PRs by @freesig in a way that isn't compatible with the changes here.

**Comment by Voxelot** [comment]
decided to merge this anyways so we can release fuel-vm before too many breaking changes accumulate.

**Pull request merged**
