### PR TITLE
Use `self` instead of `&self` during decompression

### PR DESCRIPTION
**Pull request by xgreenx**
Just move `self` during deserialization since in most cases we will do nothing with it.

### CODE REVIEW

**Review by netrome — APPROVED** [review]
Looks correct to me. However, it is not obvious to me what the benefit of doing this are. What do we gain by taking ownership/moving the compressed value as opposed to reading it over a reference?

The only obvious improvement I can see is for `PoliciesBits` where we skip a redundant dereferencing operation, but for `UtxoId` and `impl_substitutable_key` we need to create new references within the functions instead.

**Comment by xgreenx** [comment]
It has more sense in the case of messages and coins(predicate data for example, where we just move vector instead of cloning it).

**Comment by netrome** [comment]
> It has more sense in the case of messages and coins(predicate data for example, where we just move vector instead of cloning it).

Alright, makes sense. Thanks for clarifying!

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:

**Review by Dentosal — DISMISSED** [review]

**Review by netrome — APPROVED** [review]

**Review by Dentosal — APPROVED** [review]

**Pull request merged**
