### PR TITLE
Assert non-writable property of reserved registers

### PR DESCRIPTION
**Pull request by vlopes11**
All instructions that writes data to a register must be shielded by the
assertion that the register is writable

### CODE REVIEW

**Review by Dentosal — APPROVED** [review]

**Comment by Voxelot** [comment]
When fixing bugs like these we should include test cases to verify repro and prevent the issue from happening again

**Comment by Dentosal** [comment]
Maybe we could have one big test that checks that all instructions honor the read-only properties of reserved registers?

**Comment by vlopes11** [comment]
We need some serious test coverage for a lot of other stuff we aren't checking now. Covering these micro edges is a project by itself and can't be solved here - unless we just add tests for these instructions, which will neither grant the assertion of this rule nor cover the other edges

**Comment by Voxelot** [comment]
I think it's a good practice to capture each bug discovered into a test case. Otherwise we're just eyeballing and manually testing fixes. Since bugs expose edge cases, that's the perfect time to add coverage for the edge case that was uncovered.

**Pull request merged**
