### PR TITLE
Add ClusterFuzzLite in CI featuring PR fuzzing, batch fuzzing and fuzz coverage reports

### PR DESCRIPTION
**Pull request by netrome**
Supersedes https://github.com/FuelLabs/fuel-vm/pull/727

This PR introduces fuzzing in our CI using ClusterFuzzLite, roughly following the instructions outlined in the [ClusterFuzzLite Github Actions docs](https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/github-actions/).

### Before requesting review
- [x] I have reviewed the code myself

### CODE REVIEW

**Review by xgreenx — APPROVED** [review]
It would be nice to verify somehow that if fuzzers fails, it will report about it. Could you try to introduce a bug in a separate PR which fuzzer will catch, please?=)

**Comment by netrome** [comment]
> It would be nice to verify somehow that if fuzzers fails, it will report about it. Could you try to introduce a bug in a separate PR which fuzzer will catch, please?=)

We had some fun doing this in this PR. Posting here for visibility: https://github.com/FuelLabs/fuel-vm/pull/846

**Review by AurelienFT — APPROVED** [review]

**Comment by maxammann** [comment]
@netrome Hi! Would you be open to chat about how this works our for Fuel in a few months from now?

**Comment by netrome** [comment]
> @netrome Hi! Would you be open to chat about how this works our for Fuel in a few months from now?

Sure thing, I'd be happy to. Right now we're experiencing some issues with empty coverage uploads https://github.com/FuelLabs/fuel-fuzzing-corpus/commit/bf288985f3b94e8048d36b457c750cf7af6865b5 is that anything you recognize from other projects?

**Comment by maxammann** [comment]
> > @netrome Hi! Would you be open to chat about how this works our for Fuel in a few months from now?
> 
> Sure thing, I'd be happy to. Right now we're experiencing some issues with empty coverage uploads [FuelLabs/fuel-fuzzing-corpus@bf28898](https://github.com/FuelLabs/fuel-fuzzing-corpus/commit/bf288985f3b94e8048d36b457c750cf7af6865b5) is that anything you recognize from other projects?

Sadly does not ring a bell for me :/

**Comment by netrome** [comment]
> Sadly does not ring a bell for me :/

Oh well, we'll figure it out.

**Pull request merged**
